custom:
  env:
    var1: 2
    var2: 8

logging:
  level:
    root: INFO
    com.example.services: DEBUG
  console:
    ansi:
      enabled: true

logging.file:
  path: logs
  name: myCustomLogs/application.log